import {Metadata} from 'next';
import {cookies} from 'next/headers';
import React, {Suspense} from 'react';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter';
import {ThemeProvider} from '@mui/material/styles';
import {Refine} from '@refinedev/core';
import {RefineKbar, RefineKbarProvider} from '@refinedev/kbar';
import {notificationProvider, RefineSnackbarProvider} from '@refinedev/mui';
import {dataProvider} from '@providers/data-provider';
import {ColorModeContextProvider} from '@contexts/color-mode';
import {themeMui} from '@themes/themeMui';
import {Open_Sans} from 'next/font/google';

export const metadata: Metadata = {
  title: 'Refine',
  description: 'Generated by create refine app',
  icons: {
    icon: '/favicon.ico',
  },
};

const openSans = Open_Sans({
  display: 'swap',
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');
  const defaultMode = theme?.value === 'dark' ? 'dark' : 'light';

  return (
    <html lang="en">
      <body className={openSans.className}>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <AppRouterCacheProvider>
                  <ThemeProvider theme={themeMui}>
                    <Refine
                      dataProvider={dataProvider}
                      notificationProvider={notificationProvider}
                      resources={[]}
                      options={{
                        syncWithLocation: true,
                        warnWhenUnsavedChanges: true,
                        useNewQueryKeys: true,
                        projectId: 'l2t4gY-rjYxa1-SA2Zka',
                      }}
                    >
                      {children}
                      <RefineKbar />
                    </Refine>
                  </ThemeProvider>
                </AppRouterCacheProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
